### ISSUE TITLE
Pre-trained models / more easy usage

### ISSUE THREAD

**Issue by flipz357** [zzshou/AMRSim#2]
Hi, 

very cool work!

is there any chance you could release a pre-trained model and maybe a wrapper script, so that metric can be run more simply, like from command line?

**Comment by zzshou** [comment]
Hi Dr. Juri Opitz,

It's quite good to hear from you. I've read a lot of your work that inspire my research and your insights have really shaped how I understand AMR evaluation.
Actually, our trained model is available through this link (https://drive.google.com/file/d/1klTrvv3hpIPxaCoMbRI7IJDme-Vq3UPS/view?usp=share_link) and evaluation can be used through two steps:
1. preprocess
cd preprocess
python amr2json.py -src <amr_file> -tgt <amr_file>

2. evaluation
cd sentence_transformers
python test_amrsim.py

Setting up the environment and installing packages might be a bit tricky. If you have any further questions, don't hesitate to reach out.

**Comment by flipz357** [comment]
Thanks Ziyi, I must have overlooked it. Maybe it could help make it a bit more clear in the Readme with slightly more precise section headers:

```
## Computing AMR Similarity

### Preprocess
...

### Returning Similarity with pre-trained model
...

### Training a Similarity model from scratch
...
```

Best wishes, Juri
