### ISSUE TITLE
Question about dataset of "STSB"

### ISSUE THREAD

**Issue by Astrology-Team** [zzshou/AMRSim#3]
Hello, in your paper, it is described that "We experiment with AMRSim on the transformed STSB (Baudiš et al., 2016) and SICK (Marelli et al., 2014) datasets, which contain pairs of AMR graphs and corresponding similarity scores."

However, I couldn't find the relevant data files for STSB in the repository. After downloading STSB from the internet, I found that it only contains similarity scores between sentences. May I ask if you are using the similarity scores between sentences directly as the similarity scores for pairs of AMR graphs. or there is another preprocessing?

Additionally, after my processing, the data format of STSB is like this:

{"score": "5.0", "ref1": "A man with a hard hat is dancing.", "graph_ref1": {"amr_simple": "dance-01 :ARG0 man :ARG0-of wear-01 :ARG1 hat :mod hard", "triples": "[[0, 1, \"d\"], [1, 0, \"r\"], [1, 2, \"d\"], [2, 1, \"r\"], [2, 3, \"d\"], [3, 2, \"r\"], [3, 4, \"d\"], [4, 3, \"r\"], [4, 5, \"d\"], [5, 4, \"r\"], [5, 6, \"d\"], [6, 5, \"r\"], [6, 7, \"d\"], [7, 6, \"r\"], [7, 8, \"d\"], [8, 7, \"r\"]]"}, "ref2": "A man wearing a hard hat is dancing.", "graph_ref2": {"amr_simple": "dance-01 :ARG0 man :ARG0-of wear-01 :ARG1 hat :ARG1-of hard-04", "triples": "[[0, 1, \"d\"], [1, 0, \"r\"], [1, 2, \"d\"], [2, 1, \"r\"], [2, 3, \"d\"], [3, 2, \"r\"], [3, 4, \"d\"], [4, 3, \"r\"], [4, 5, \"d\"], [5, 4, \"r\"], [5, 6, \"d\"], [6, 5, \"r\"], [6, 7, \"d\"], [7, 6, \"r\"], [7, 8, \"d\"], [8, 7, \"r\"]]"}}

**Comment by Astrology-Team** [comment]
Besides, the BAMBOO Benchmark also directly use the similarity scores between sentences directly as the similarity scores for pairs of AMR graphs. I wonder if this is workable.

**Comment by zzshou** [comment]
Yes, we directly employ the scores assigned to sentences. The Semantic Textual Similarity (STS) tasks include human-annotated semantic similarity scores for sentences. Our assumption is that AMR effectively captures the semantic content of sentences. Therefore, we believe that the semantic similarity scores assigned to sentences can be directly used for the similarity evaluation of their corresponding AMR graphs.

**Comment by Astrology-Team** [comment]
Thanks, cool work!
